
apiVersion: apps/v1
kind: Deployment        # We are testing the Deployment resource type
metadata:
  name: zookeeper-deployment  # A name must be given to the Job type in the metadata section

spec:                     # This is the specification where we can even put the number of replicas
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-app
  minReadySeconds: 30

  template:
    metadata:
      labels:
        app: zookeeper-app
    spec:
      containers:
      - name: kafka
        image: kafka
        imagePullPolicy: Never
        command: ["/bin/sh"]
        args: ["/kafka/bin/zookeeper-server-start.sh", "/kafka/config/zookeeper.properties"]
        ports:
        - containerPort: 2181