# clear log + start db 
- hosts: MyChameleonVMs
  remote_user: cc 
  become: true 

  tasks:
  - name: Clear Logs
    command: rm -fr /tmp/zookeeper/ /tmp/kafka*

# run zookeeper + kafka on vm2
- hosts: MyCC2
  remote_user:  cc  

  tasks:
  - name: Run Zookeeper on VM2
    command: /home/cc/kafka_2.13-3.0.0/bin/zookeeper-server-start.sh /home/cc/kafka_2.13-3.0.0/config/zookeeper.properties  # run zookeeper vm2 
    async: 1000
    poll: 0 #might need to adjust path
    
  - name: Run Kafka on VM2
    command: /home/cc/kafka_2.13-3.0.0/bin/kafka-server-start.sh /home/cc/kafka_2.13-3.0.0/config/server.properties # run kafka on vm2
    async: 1000
    poll: 0 #might need to adjust path

# run kafka + couchdb on vm3
- hosts: MyCC3
  remote_user:  cc  

  tasks:
  - name: Run Kafka on VM3
    command: /home/cc/kafka_2.13-3.0.0/bin/kafka-server-start.sh /home/cc/kafka_2.13-3.0.0/config/server.properties # run kafka on vm3
    async: 1000
    poll: 0 #might need to adjust path
  
  - name: restart couchdb
    become: yes
    service:
      name: couchdb
      state: restarted


#run consumer code on vm2
- hosts: MyCC2
  remote_user:  cc  
  become: true 

  tasks:
  - name: run consumer code on VM3
    command: python3 /home/cc/consumer.py
    async: 1000
    poll: 0


