- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Add an apt signing key for Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add apt repository for stable version
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install docker and its dependecies
  apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io
  notify:
    - docker status

- name: Add cc user to docker group
  user:
    name: cc
    group: docker

- name: Create daemon.json file to set docker properties
  copy:
    content: ""
    dest: /etc/docker/daemon.json
    force: false

- name: Edit docker.service file to use systemd-based cgroup
  ansible.builtin.lineinfile:
    path: /etc/docker/daemon.json
    insertafter: '{'
    line: '{"exec-opts": ["native.cgroupdriver=systemd"]}'

- debug: 
    var: json.stdout


- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0